<?php

/**
 * Implements hook_menu().
 */

function qcon_oo_menu() {
    $items = array();

  $items['quakecon/byoc'] = array(
    'title' => 'Quakecon BYOC 2015',
    'access callback' => 'qcon_oo_access',
    //'access arguments' => array('administer theme assignments'),
    'page callback' => 'qcon_oo_main',
      'file' => 'qcon_oo.page.inc',
      'type' => MENU_CALLBACK,
  );
  
  $items['quakecon/byocoo/autocomplete'] = array(
    'title' => 'BYOC Autocomplete',
    'access callback' => 'qcon_oo_access',
    //'access arguments' => array('administer theme assignments'),
    'page callback' => 'qcon_oo_autocomplete',
      'type' => MENU_CALLBACK,
  );
  
  $items['quakecon/byocoo/clanautocomplete'] = array(
    'title' => 'BYOC Clan Autocomplete',
    'access callback' => 'qcon_oo_access',
    //'access arguments' => array('administer theme assignments'),
    'page callback' => 'qcon_oo_clan',
      'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function qcon_oo_access() {
//    global $user;
//    if ($user->uid != 1) {
//        return FALSE;
//    }
//    else {
//        return TRUE;
//    }
  return TRUE;
}

function qcon_oo_autocomplete($string) {
  $matches = array();
  //search table `cities` for cities that begin with the letters the user enters in the form
  db_set_active('qcon');
  
  $result = db_select('players', 'a')
    ->fields('a', array(
        'id',
        'seat',
        'name',
        'clan',
        ))
    ->condition('name', '%' . db_like($string) . '%', 'LIKE')
    ->range(0,15)
    ->execute();

  // save the query to matches
  foreach ($result as $row) {
    $clan = (!empty($row->clan)) ? "[" . check_plain($row->clan) . "] " : '';
    $string = check_plain($row->seat) . " | " . $clan . check_plain($row->name);
    $matches[$string] = $string;
  }
  db_set_active();
  // Return the result to the form in json
  drupal_json_output($matches);
}
//->condition('clan', '%' . db_like($string) . '%', 'LIKE')

function qcon_oo_clan($string) {
  $clans = array();
  //search table `cities` for cities that begin with the letters the user enters in the form
  db_set_active('qcon');
  
  $result = db_select('players', 'a')
    ->distinct()
    ->fields('a', array(
        'clan',
        ))
    ->condition('clan', '%' . db_like($string) . '%', 'LIKE')
    ->range(0,15)
    ->execute();

  // save the query to matches
  foreach ($result as $row) {
    $clan = (!empty($row->clan)) ? check_plain($row->clan) : '';
    $clans[$clan] = $clan;
  }
  db_set_active();
  // Return the result to the form in json
  drupal_json_output($clans);
}
